/*
 *
 * Patron constants
 *
 */

export const DEFAULT_ACTION = 'app/Patron/DEFAULT_ACTION';
export const REQUEST_MY_LIBRARIES = 'app/Patron/REQUEST_MY_LIBRARIES';
export const REQUEST_MY_LIBRARIES_SUCCESS = 'app/Patron/REQUEST_MY_LIBRARIES_SUCCESS';
export const REQUEST_MY_ACTIVE_LIBRARIES_OPTIONLIST='app/Patron/REQUEST_MY_ACTIVE_LIBRARIES_OPTIONLIST';
export const REQUEST_MY_ACTIVE_LIBRARIES_OPTIONLIST_SUCCESS='app/Patron/REQUEST_MY_ACTIVE_LIBRARIES_OPTIONLIST_SUCCESS';
export const REQUEST_GET_MY_LIBRARY = 'app/Patron/REQUEST_GET_MY_LIBRARY';
export const REQUEST_GET_MY_LIBRARY_SUCCESS = 'app/Patron/REQUEST_GET_MY_LIBRARY_SUCCESS';
export const REQUEST_GET_LIBRARY_OPTIONLIST = 'app/Patron/REQUEST_GET_LIBRARY_OPTIONLIST';
export const REQUEST_GET_LIBRARY_OPTIONLIST_SUCCESS = 'app/Patron/REQUEST_GET_LIBRARY_OPTIONLIST_SUCCESS';
export const REQUEST_GET_LIBRARY_DELIVERIES = 'app/Patron/REQUEST_GET_LIBRARY_DELIVERIES';
export const REQUEST_GET_LIBRARY_DELIVERIES_SUCCESS = 'app/Patron/REQUEST_GET_LIBRARY_DELIVERIES_SUCCESS';
export const REQUEST_GET_LABELS_OPTIONLIST = 'app/Patron/REQUEST_GET_LABELS_OPTIONLIST';
export const REQUEST_GET_LABELS_OPTIONLIST_SUCCESS = 'app/Patron/REQUEST_GET_LABELS_OPTIONLIST_SUCCESS';
export const REQUEST_GET_GROUPS_OPTIONLIST = 'app/Patron/REQUEST_GET_GROUPS_OPTIONLIST';
export const REQUEST_GET_GROUPS_OPTIONLIST_SUCCESS = 'app/Patron/REQUEST_GET_GROUPS_OPTIONLIST_SUCCESS';
export const REQUEST_REMOVE_REFERENCE_LABEL='app/Patron/REQUEST_REMOVE_REFERENCE_LABEL';
export const REQUEST_REMOVE_REFERENCE_GROUP='app/Patron/REQUEST_REMOVE_REFERENCE_GROUP';
export const REQUEST_APPLY_LABELS_TO_REFERENCES='app/Patron/REQUEST_APPLY_LABELS_TO_REFERENCES';
export const REQUEST_APPLY_GROUPS_TO_REFERENCES='app/Patron/REQUEST_APPLY_GROUPS_TO_REFERENCES';
export const REQUEST_POST_LABEL = 'app/Patron/REQUEST_POST_LABEL';
export const REQUEST_UPDATE_LABEL = 'app/Patron/REQUEST_UPDATE_LABEL';
export const REQUEST_REMOVE_LABEL = 'app/Patron/REQUEST_REMOVE_LABEL';

export const REQUEST_POST_GROUP = 'app/Patron/REQUEST_POST_GROUP';
export const REQUEST_UPDATE_GROUP = 'app/Patron/REQUEST_UPDATE_GROUP';
export const REQUEST_REMOVE_GROUP = 'app/Patron/REQUEST_REMOVE_GROUP';


export const REQUEST_ACCESS_TO_LIBRARIES = 'app/Patron/REQUEST_ACCESS_TO_LIBRARIES';
export const REQUEST_UPDATE_ACCESS_TO_LIBRARIES= 'app/Patron/REQUEST_UPDATE_ACCESS_TO_LIBRARIES';
export const REQUEST_DELETE_ACCESS_TO_LIBRARIES= 'app/Patron/REQUEST_DELETE_ACCESS_TO_LIBRARIES';
export const REQUEST_REFERENCES_LIST = 'app/Patron/REQUEST_REFERENCES_LIST';
export const REQUEST_REFERENCES_LIST_SUCCESS = 'app/Patron/REQUEST_REFERENCES_LIST_SUCCESS';
export const REQUEST_REQUESTS_LIST = 'app/Patron/REQUEST_REQUESTS_LIST';
export const REQUEST_REQUESTS_LIST_SUCCESS = 'app/Patron/REQUEST_REQUESTS_LIST_SUCCESS';
export const REQUEST_GET_REQUEST = 'app/Patron/REQUEST_GET_REQUEST';
export const REQUEST_GET_REQUEST_SUCCESS = 'app/Patron/REQUEST_GET_REQUEST_SUCCESS';
export const REQUEST_UPDATE_REQUEST = 'app/Patron/REQUEST_UPDATE_REQUEST';
export const REQUEST_ARCHIVE_REQUEST = 'app/Patron/REQUEST_ARCHIVE_REQUEST';
export const REQUEST_POST_REQUEST = 'app/Patron/REQUEST_POST_REQUEST';
export const REQUEST_CHANGE_STATUS_REQUEST = 'app/Patron/REQUEST_CHANGE_STATUS_REQUEST';


export const REQUEST_GET_REFERENCE = 'app/Patron/REQUEST_GET_REFERENCE';
export const REQUEST_GET_REFERENCE_SUCCESS = 'app/Patron/REQUEST_GET_REFERENCE_SUCCESS';

export const REQUEST_DELETE_REFERENCE='app/Patron/REQUEST_DELETE_REFERENCE';

export const REQUEST_POST_REFERENCES = 'app/Patron/REQUEST_POST_REFERENCES';
export const REQUEST_UPDATE_REFERENCES = 'app/Patron/REQUEST_UPDATE_REFERENCES';
export const REQUEST_ERROR = 'app/Patron/REQUEST_ERROR';
export const REQUEST_SUCCESS = 'app/Patron/REQUEST_SUCCESS';
export const STOP_LOADING = 'app/Patron/STOP_LOADING';
