/*
 *
 * Patron constants
 *
 */

export const DEFAULT_ACTION = 'app/Patron/DEFAULT_ACTION';
export const REQUEST_MY_LIBRARIES = 'app/Patron/REQUEST_MY_LIBRARIES';
export const REQUEST_MY_LIBRARIES_SUCCESS = 'app/Patron/REQUEST_MY_LIBRARIES_SUCCESS';
export const REQUEST_GET_LIBRARIES_LIST = 'app/Patron/REQUEST_GET_LIBRARIES_LIST';
export const REQUEST_GET_LIBRARIES_LIST_SUCCESS = 'app/Patron/REQUEST_GET_LIBRARIES_LIST_SUCCESS';
export const REQUEST_ACCESS_TO_LIBRARIES = 'app/Patron/REQUEST_ACCESS_TO_LIBRARIES';
export const REQUEST_REFERENCES_LIST = 'app/Patron/REQUEST_REFERENCES_LIST';
export const REQUEST_REFERENCES_LIST_SUCCESS = 'app/Patron/REQUEST_REFERENCES_LIST_SUCCESS';
export const REQUEST_GET_REFERENCE = 'app/Patron/REQUEST_GET_REFERENCE';
export const REQUEST_GET_REFERENCE_SUCCESS = 'app/Patron/REQUEST_GET_REFERENCE_SUCCESS';
export const REQUEST_POST_REFERENCES = 'app/Patron/REQUEST_POST_REFERENCES';
export const REQUEST_UPDATE_REFERENCES = 'app/Patron/REQUEST_UPDATE_REFERENCES';
export const REQUEST_ERROR = 'app/Patron/REQUEST_ERROR';
export const REQUEST_SUCCESS = 'app/Patron/REQUEST_SUCCESS';
export const STOP_LOADING = 'app/Patron/STOP_LOADING';
