/*
 *
 * Patron constants
 *
 */

export const DEFAULT_ACTION = 'app/Patron/DEFAULT_ACTION';
export const REQUEST_MY_LIBRARIES = 'app/Patron/REQUEST_MY_LIBRARIES';
export const REQUEST_MY_LIBRARIES_SUCCESS = 'app/Patron/REQUEST_MY_LIBRARIES_SUCCESS';
export const REQUEST_GET_LIBRARIES_LIST = 'app/Patron/REQUEST_GET_LIBRARIES_LIST';
export const REQUEST_GET_LIBRARIES_LIST_SUCCESS = 'app/Patron/REQUEST_GET_LIBRARIES_LIST_SUCCESS';
export const REQUEST_ACCESS_TO_LIBRARIES = 'app/Patron/REQUEST_ACCESS_TO_LIBRARIES';
export const REQUEST_ACCESS_TO_LIBRARIES_SUCCESS = 'app/Patron/REQUEST_ACCESS_TO_LIBRARIES_SUCCESS';
export const REQUEST_ERROR = 'app/Patron/REQUEST_ERROR';
export const STOP_LOADING = 'app/Patron/STOP_LOADING';
