/*
 *
 * constants
 *
 */

export const DEFAULT_ACTION = 'app/RegisterLibrary/DEFAULT_ACTION';
export const REQUEST_POST_PUBLIC_LIBRARY = 'app/RegisterLibrary/REQUEST_POST_PUBLIC_LIBRARY';
export const REQUEST_POST_PUBLIC_LIBRARY_SUCCESS = 'app/RegisterLibrary/REQUEST_POST_PUBLIC_LIBRARY_SUCCESS';
export const REQUEST_GET_INSTITUTIONS_TYPE_COUNTRY_OPTIONLIST = 'app/RegisterLibrary/REQUEST_GET_INSTITUTIONS_TYPE_COUNTRY_OPTIONLIST';
export const REQUEST_GET_INSTITUTIONS_TYPE_COUNTRY_OPTIONLIST_SUCCESS = 'app/RegisterLibrary/REQUEST_GET_INSTITUTIONS_TYPE_COUNTRY_OPTIONLIST_SUCCESS';
export const REQUEST_INSTITUTIONSTYPES_OPTIONLIST = 'app/RegisterLibrary/REQUEST_INSTITUTIONSTYPES_OPTIONLIST';
export const REQUEST_INSTITUTIONSTYPES_OPTIONLIST_SUCCESS = 'app/RegisterLibrary/REQUEST_INSTITUTIONSTYPES_OPTIONLIST_SUCCESS';
export const REQUEST_GET_LIBRARY_PROJECTS_OPTIONLIST = 'app/RegisterLibrary/REQUEST_GET_LIBRARY_PROJECTS_OPTIONLIST';
export const REQUEST_GET_LIBRARY_PROJECTS_OPTIONLIST_SUCCESS = 'app/RegisterLibrary/REQUEST_GET_LIBRARY_PROJECTS_OPTIONLIST_SUCCESS';


export const REQUEST_GET_LIBRARY_IDENTIFIER_TYPES_OPTIONLIST = 'app/RegisterLibrary/REQUEST_GET_LIBRARY_IDENTIFIER_TYPES_OPTIONLIST';
export const REQUEST_GET_LIBRARY_IDENTIFIER_TYPES_OPTIONLIST_SUCCESS = 'app/RegisterLibrary/REQUEST_GET_LIBRARY_IDENTIFIER_TYPES_OPTIONLIST_SUCCESS';



export const REQUEST_SEARCH_PLACES_BY_TEXT="app/RegisterLibrary/REQUEST_SEARCH_PLACES_BY_TEXT";
export const REQUEST_SEARCH_PLACES_BY_TEXT_SUCCESS="app/RegisterLibrary/REQUEST_SEARCH_PLACES_BY_TEXT_SUCCESS";
export const REQUEST_SEARCH_PLACES_BY_TEXT_FAIL="app/RegisterLibrary/REQUEST_SEARCH_PLACES_BY_TEXT_FAIL";
export const REQUEST_GET_LIBRARY_LIST = 'app/RegisterLibrary/REQUEST_GET_LIBRARY_LIST';
export const REQUEST_GET_LIBRARY_LIST_SUCCESS = 'app/RegisterLibrary/REQUEST_GET_LIBRARY_LIST_SUCCESS';
export const REQUEST_ERROR = 'app/RegisterLibrary/REQUEST_ERROR';
export const REQUEST_SUCCESS = 'app/RegisterLibrary/REQUEST_SUCCESS';
export const STOP_LOADING = 'app/RegisterLibrary/STOP_LOADING';
