FROM node:8.15.1
# dovrebbe avere la npm v5.3 integrata

WORKDIR /usr/src

#RUN apt-get update; apt-get install -y

COPY . /usr/src/app
WORKDIR /usr/src/app

#RUN npm install

#RUN npm install -g cross-env


#RUN npm run setup


#RUN npm run build:docker
#RUN npm run build

#START
#CMD npm run start:docker
#CMD [ "npm", "start" ]
