export const REQUEST_GET_REFERENCE = 'app/Reference/REQUEST_GET_REFERENCE';
export const REQUEST_GET_REFERENCE_SUCCESS = 'app/Reference/REQUEST_GET_REFERENCE_SUCCESS';

export const REQUEST_FIND_REFERENCE_BY_ID="app/Reference/REQUEST_FIND_REFERENCE_BY_ID";
export const REQUEST_FIND_REFERENCE_BY_ID_SUCCESS="app/Reference/REQUEST_FIND_REFERENCE_BY_ID_SUCCESS";

