<?php namespace App\Models\Libraries;

use App\Models\BaseObserver;
use \Auth;
use Str;

class UserObserver extends BaseObserver
{
    protected $rules = [
        'name' => 'required|max:255',
        'surname' => 'required|max:255',
        'email' => 'sometimes|required|email|max:255|unique:users,email',
        'password' => 'required|confirmed|min:8|max:60',

        'country_id' => 'nullable|exists:countries',
        'address' => 'nullable|max:255',
        'town' => 'nullable|max:255',
        'district' => 'nullable|max:255',
        'postcode' => 'nullable|max:255',
        'state' => 'nullable|max:255',
        'phone' => 'nullable|max:255',
        'mobile' => 'nullable|max:255',

        'nationality' => 'nullable|integer|exists:countries,id',
        'phone' => 'nullable|max:255',
        'preflang' => 'nullable|max:255', // TODO: language config or DB

        'privacy_policy_accepted' => 'required|date',
    ];


    protected function setConditionalRules($model){
        $id = $model->getKey();

        if($model->exists)
        {
            // remove password from rules in case of update
            $rules = array_except($this->validator->getRules(), ['password']);
            $this->validator->setRules($rules);
        }

        foreach(['email'] as $field)
        {
            $this->validator->sometimes($field, $this->rules[$field].",$id", function($input) use($model, $field)
            {
                if($model->exists)
                {
                    $rules = array_except($this->validator->getRules(), [$field]);
                    $this->validator->setRules($rules);
                    return true;
                }
                return false;
            });
        }
    }

    public function creating($model)
    {
        $model->password = \Hash::make($model->password);
        return parent::creating($model); // TODO: Change the autogenerated stub
    }

    public function created($model)
    {
//        if(!is_null(config('nilde.user_default_roles')))
//        {
//            $default_role = $model->roles()->getModel()->where('id',config('nilde.user_default_roles'))->get();
//            $model->roles()->attach($default_role);
//        }
    }

    public function updating($model)
    {
        //prevent update password in any case!
        if(isset($model->password) || empty($model->password))
            unset($model->password);
    }

    public function saving($model)
    {
        //generate password if not defined, only if model isn't created
        if( (empty($model->password) || is_null($model->password)) && !$model->exists)
        {
            $password = Str::random(12);
            $model->password = $password;
            $model->password_confirmation = $password;
        }

        //NOTE: it's important because trigger the validation
        $parent_saving = parent::saving($model);

        //prevent send of variable password_confirmation in a database row.
        if(isset($model->password_confirmation) || empty($model->password_confirmation) || is_null($model->password_confirmation)) {
            unset($model->password_confirmation);
        }

        return $parent_saving;
    }

}
