/*
 *
 * Admin constants
 *
 */

export const DEFAULT_ACTION = 'app/Admin/DEFAULT_ACTION';
export const REQUEST_USERS_LIST = 'app/Admin/REQUEST_USERS_LIST';
export const REQUEST_USERS_LIST_SUCCESS = 'app/Admin/REQUEST_USERS_LIST_SUCCESS';
export const REQUEST_USER = 'app/Admin/REQUEST_USER';
export const REQUEST_USER_SUCCESS = 'app/Admin/REQUEST_USER_SUCCESS';
export const REQUEST_UPDATE_USER = 'app/Admin/REQUEST_UPDATE_USER';
export const REQUEST_UPDATE_USER_SUCCESS = 'app/Admin/REQUEST_UPDATE_USER_SUCCESS';

export const REQUEST_POST_USER = 'app/Admin/REQUEST_POST_USER';
export const REQUEST_POST_USER_SUCCESS = 'app/Admin/REQUEST_POST_USER_SUCCESS';

export const REQUEST_GET_LIBRARY = 'app/Admin/REQUEST_GET_LIBRARY';
export const REQUEST_GET_LIBRARY_SUCCESS = 'app/Admin/REQUEST_GET_LIBRARY_SUCCESS';
export const REQUEST_POST_LIBRARY = 'app/Admin/REQUEST_POST_LIBRARY';
export const REQUEST_POST_LIBRARY_SUCCESS = 'app/Admin/REQUEST_POST_LIBRARY_SUCCESS';
export const REQUEST_UPDATE_LIBRARY = 'app/Admin/REQUEST_UPDATE_LIBRARY';
export const REQUEST_UPDATE_LIBRARY_SUCCESS = 'app/Admin/REQUEST_UPDATE_LIBRARY_SUCCESS';
export const REQUEST_GET_LIBRARIES_LIST = 'app/Admin/REQUEST_GET_LIBRARIES_LIST';
export const REQUEST_GET_LIBRARIES_LIST_SUCCESS = 'app/Admin/REQUEST_GET_LIBRARIES_LIST_SUCCESS';

export const REQUEST_GET_INSTITUTION_TYPE_LIST = 'app/Admin/REQUEST_GET_INSTITUTION_TYPE_LIST';
export const REQUEST_GET_INSTITUTION_TYPE_LIST_SUCCESS = 'app/Admin/REQUEST_GET_INSTITUTION_TYPE_LIST_SUCCESS';
export const REQUEST_GET_INSTITUTIONS_LIST = 'app/Admin/REQUEST_GET_INSTITUTIONS_LIST';
export const REQUEST_GET_INSTITUTIONS_LIST_SUCCESS = 'app/Admin/REQUEST_GET_INSTITUTIONS_LIST_SUCCESS';
export const REQUEST_GET_INSTITUTION = 'app/Admin/REQUEST_GET_INSTITUTION';
export const REQUEST_GET_INSTITUTION_SUCCESS = 'app/Admin/REQUEST_GET_INSTITUTION_SUCCESS';
export const REQUEST_GET_INSTITUTIONS_SELECT_LIST = 'app/Admin/REQUEST_GET_INSTITUTIONS_SELECT_LIST';
export const REQUEST_GET_INSTITUTIONS_SELECT_LIST_SUCCESS = 'app/Admin/REQUEST_GET_INSTITUTIONS_SELECT_LIST_SUCCESS';
export const REQUEST_GET_COUNTRIES_SELECT_LIST = 'app/Admin/REQUEST_GET_COUNTRIES_SELECT_LIST';
export const REQUEST_GET_COUNTRIES_SELECT_LIST_SUCCESS = 'app/Admin/REQUEST_GET_COUNTRIES_SELECT_LIST_SUCCESS';
export const REQUEST_POST_INSTITUTION = 'app/Admin/REQUEST_POST_INSTITUTION';

export const REQUEST_GET_PROJECT = 'app/Admin/REQUEST_GET_PROJECT';
export const REQUEST_GET_PROJECT_SUCCESS = 'app/Admin/REQUEST_GET_PROJECT_SUCCESS';
export const REQUEST_POST_PROJECT = 'app/Admin/REQUEST_POST_PROJECT';
export const REQUEST_POST_PROJECT_SUCCESS = 'app/Admin/REQUEST_POST_PROJECT_SUCCESS';
export const REQUEST_UPDATE_PROJECT = 'app/Admin/REQUEST_UPDATE_PROJECT';
export const REQUEST_UPDATE_PROJECT_SUCCESS = 'app/Admin/REQUEST_UPDATE_PROJECT_SUCCESS';
export const REQUEST_GET_PROJECTS_LIST = 'app/Admin/REQUEST_GET_PROJECTS_LIST';
export const REQUEST_GET_PROJECTS_LIST_SUCCESS = 'app/Admin/REQUEST_GET_PROJECTS_LIST_SUCCESS';


export const REQUEST_SUCCESS = 'app/Admin/REQUEST_SUCCESS';
export const STOP_LOADING = 'app/Admin/STOP_LOADING';
