/*
 *
 * Admin constants
 *
 */

export const DEFAULT_ACTION = 'app/Admin/DEFAULT_ACTION';
export const REQUEST_USERS_LIST = 'app/Admin/REQUEST_USERS_LIST';
export const REQUEST_USERS_LIST_SUCCESS = 'app/Admin/REQUEST_USERS_LIST_SUCCESS';
export const REQUEST_USER = 'app/Admin/REQUEST_USER';
export const REQUEST_USER_SUCCESS = 'app/Admin/REQUEST_USER_SUCCESS';
export const REQUEST_UPDATE_USER = 'app/Admin/REQUEST_UPDATE_USER';
export const REQUEST_UPDATE_USER_SUCCESS = 'app/Admin/REQUEST_UPDATE_USER_SUCCESS';

export const REQUEST_USERS_OPTIONLIST = 'app/Admin/REQUEST_USERS_OPTIONLIST';
export const REQUEST_USERS_OPTIONLIST_SUCCESS = 'app/Admin/REQUEST_USERS_OPTIONLIST_SUCCESS';

export const REQUEST_POST_USER = 'app/Admin/REQUEST_POST_USER';
export const REQUEST_POST_USER_SUCCESS = 'app/Admin/REQUEST_POST_USER_SUCCESS';

export const REQUEST_GET_ROLES = 'app/Admin/REQUEST_GET_ROLES';
export const REQUEST_GET_ROLES_SUCCESS = 'app/Admin/REQUEST_GET_ROLES_SUCCESS';

export const REQUEST_GET_LIBRARY = 'app/Admin/REQUEST_GET_LIBRARY';
export const REQUEST_GET_LIBRARY_SUCCESS = 'app/Admin/REQUEST_GET_LIBRARY_SUCCESS';
export const REQUEST_POST_LIBRARY = 'app/Admin/REQUEST_POST_LIBRARY';
export const REQUEST_POST_LIBRARY_SUCCESS = 'app/Admin/REQUEST_POST_LIBRARY_SUCCESS';
export const REQUEST_UPDATE_LIBRARY = 'app/Admin/REQUEST_UPDATE_LIBRARY';
export const REQUEST_UPDATE_LIBRARY_SUCCESS = 'app/Admin/REQUEST_UPDATE_LIBRARY_SUCCESS';
export const REQUEST_GET_LIBRARIES_LIST = 'app/Admin/REQUEST_GET_LIBRARIES_LIST';
export const REQUEST_GET_LIBRARIES_LIST_SUCCESS = 'app/Admin/REQUEST_GET_LIBRARIES_LIST_SUCCESS';
export const REQUEST_DELETE_LIBRARY = 'app/Admin/REQUEST_DELETE_LIBRARY';
export const REQUEST_STATUS_CHANGE_LIBRARY="app/Admin/REQUEST_STATUS_CHANGE_LIBRARY";

export const REQUEST_POST_PUBLIC_LIBRARY = 'app/Admin/REQUEST_POST_PUBLIC_LIBRARY';
export const REQUEST_POST_PUBLIC_LIBRARY_SUCCESS = 'app/Admin/REQUEST_POST_PUBLIC_LIBRARY_SUCCESS';

export const REQUEST_GET_INSTITUTION_TYPE_LIST = 'app/Admin/REQUEST_GET_INSTITUTION_TYPE_LIST';
export const REQUEST_GET_INSTITUTION_TYPE_LIST_SUCCESS = 'app/Admin/REQUEST_GET_INSTITUTION_TYPE_LIST_SUCCESS';

export const REQUEST_GET_INSTITUTIONS_LIST = 'app/Admin/REQUEST_GET_INSTITUTIONS_LIST';
export const REQUEST_GET_INSTITUTIONS_LIST_SUCCESS = 'app/Admin/REQUEST_GET_INSTITUTIONS_LIST_SUCCESS';


export const REQUEST_GET_LIBRARY_IDENTIFIER_TYPES_OPTIONLIST = 'app/Admin/REQUEST_GET_LIBRARY_IDENTIFIER_TYPES_OPTIONLIST';
export const REQUEST_GET_LIBRARY_IDENTIFIER_TYPES_OPTIONLIST_SUCCESS = 'app/Admin/REQUEST_GET_LIBRARY_IDENTIFIER_TYPES_OPTIONLIST_SUCCESS';


export const REQUEST_STATUS_CHANGE_INSTITUTION="app/Admin/REQUEST_STATUS_CHANGE_INSTITUTION";
export const REQUEST_DELETE_INSTITUTION_TYPE="app/Admin/REQUEST_DELETE_INSTITUTION_TYPE";
export const REQUEST_DELETE_INSTITUTION="app/Admin/REQUEST_DELETE_INSTITUTION";

export const REQUEST_GET_INSTITUTIONS_OPTIONLIST = 'app/Admin/REQUEST_GET_INSTITUTIONS_OPTIONLIST';
export const REQUEST_GET_INSTITUTIONS_OPTIONLIST_SUCCESS = 'app/Admin/REQUEST_GET_INSTITUTIONS_OPTIONLIST_SUCCESS';

export const REQUEST_GET_INSTITUTION = 'app/Admin/REQUEST_GET_INSTITUTION';
export const REQUEST_GET_INSTITUTION_SUCCESS = 'app/Admin/REQUEST_GET_INSTITUTION_SUCCESS';

export const REQUEST_GET_INSTITUTION_TYPE = 'app/Admin/REQUEST_GET_INSTITUTION_TYPE';
export const REQUEST_GET_INSTITUTION_TYPE_SUCCESS  = 'app/Admin/REQUEST_GET_INSTITUTION_TYPE_SUCCESS';

export const REQUEST_GET_INSTITUTIONS_TYPE_COUNTRY_OPTIONLIST = 'app/Admin/REQUEST_GET_INSTITUTIONS_TYPE_COUNTRY_OPTIONLIST';
export const REQUEST_GET_INSTITUTIONS_TYPE_COUNTRY_OPTIONLIST_SUCCESS = 'app/Admin/REQUEST_GET_INSTITUTIONS_TYPE_COUNTRY_OPTIONLIST_SUCCESS';

export const UPDATE_INSTITUTION = 'app/Admin/UPDATE_INSTITUTION';
export const UPDATE_INSTITUTION_TYPE = 'app/Admin/UPDATE_INSTITUTION_TYPE';
export const REQUEST_INSTITUTION_TYPE_OPTIONLIST = 'app/Admin/REQUEST_INSTITUTION_TYPE_OPTIONLIST';
export const REQUEST_INSTITUTION_TYPE_OPTIONLIST_SUCCESS = 'app/Admin/REQUEST_INSTITUTION_TYPE_OPTIONLIST_SUCCESS';
export const REQUEST_GET_COUNTRIES_OPTIONLIST = 'app/Admin/REQUEST_GET_COUNTRIES_OPTIONLIST';
export const REQUEST_GET_COUNTRIES_OPTIONLIST_SUCCESS = 'app/Admin/REQUEST_GET_COUNTRIES_OPTIONLIST_SUCCESS';
export const REQUEST_POST_INSTITUTION = 'app/Admin/REQUEST_POST_INSTITUTION';
export const REQUEST_POST_INSTITUTION_TYPE = 'app/Admin/REQUEST_POST_INSTITUTION_TYPE';

export const REQUEST_LIBRARYSUBJECT_OPTIONLIST = 'app/Admin/REQUEST_LIBRARYSUBJECT_OPTIONLIST';
export const REQUEST_LIBRARYSUBJECT_OPTIONLIST_SUCCESS = 'app/Admin/REQUEST_LIBRARYSUBJECT_OPTIONLIST_SUCCESS';

export const REQUEST_GET_PROJECT = 'app/Admin/REQUEST_GET_PROJECT';
export const REQUEST_GET_PROJECT_SUCCESS = 'app/Admin/REQUEST_GET_PROJECT_SUCCESS';
export const REQUEST_POST_PROJECT = 'app/Admin/REQUEST_POST_PROJECT';
export const REQUEST_POST_PROJECT_SUCCESS = 'app/Admin/REQUEST_POST_PROJECT_SUCCESS';
export const REQUEST_UPDATE_PROJECT = 'app/Admin/REQUEST_UPDATE_PROJECT';
export const REQUEST_UPDATE_PROJECT_SUCCESS = 'app/Admin/REQUEST_UPDATE_PROJECT_SUCCESS';
export const REQUEST_GET_PROJECTS_LIST = 'app/Admin/REQUEST_GET_PROJECTS_LIST';
export const REQUEST_GET_PROJECTS_LIST_SUCCESS = 'app/Admin/REQUEST_GET_PROJECTS_LIST_SUCCESS';
export const REQUEST_GET_PROJECTS_OPTIONLIST = 'app/Admin/REQUEST_GET_PROJECTS_OPTIONLIST';
export const REQUEST_GET_PROJECTS_OPTIONLIST_SUCCESS = 'app/Admin/REQUEST_GET_PROJECTS_OPTIONLIST_SUCCESS';

export const REQUEST_GET_LIBRARY_PROJECTS_OPTIONLIST = 'app/Admin/REQUEST_GET_LIBRARY_PROJECTS_OPTIONLIST';
export const REQUEST_GET_LIBRARY_PROJECTS_OPTIONLIST_SUCCESS = 'app/Admin/REQUEST_GET_LIBRARY_PROJECTS_OPTIONLIST_SUCCESS';

export const REQUEST_ERROR = 'app/Admin/REQUEST_ERROR';
export const REQUEST_SUCCESS = 'app/Admin/REQUEST_SUCCESS';
export const STOP_LOADING = 'app/Admin/STOP_LOADING';


export const REQUEST_SEARCH_PLACES_BY_TEXT="app/Admin/REQUEST_SEARCH_PLACES_BY_TEXT";
export const REQUEST_SEARCH_PLACES_BY_TEXT_SUCCESS="app/Admin/REQUEST_SEARCH_PLACES_BY_TEXT_SUCCESS";
export const REQUEST_SEARCH_PLACES_BY_TEXT_FAIL="app/Admin/REQUEST_SEARCH_PLACES_BY_TEXT_FAIL";
export const REQUEST_GET_LIBRARY_LIST = 'app/Admin/REQUEST_GET_LIBRARY_LIST';
export const REQUEST_GET_LIBRARY_LIST_SUCCESS = 'app/Admin/REQUEST_GET_LIBRARY_LIST_SUCCESS';