/*
 *
 * Auth constants
 *
 */

export const REQUEST_LOGIN = 'app/Auth/REQUEST_LOGIN';
export const REQUEST_LOGOUT = 'app/Auth/REQUEST_LOGOUT';
export const REQUEST_REFRESH = 'app/Auth/REQUEST_REFRESH';
export const REQUEST_LOGIN_SUCCESS = 'app/Auth/REQUEST_LOGIN_SUCCESS';
export const REQUEST_LOGOUT_SUCCESS = 'app/Auth/REQUEST_LOGOUT_SUCCESS';
export const REQUEST_REFRESH_SUCCESS = 'app/Auth/REQUEST_REFRESH_SUCCESS';
export const REQUEST_ERROR = 'app/Auth/REQUEST_ERROR';

export const REQUEST_SIGNUP = 'app/Auth/REQUEST_SIGNUP';
export const REQUEST_SIGNUP_SUCCESS = 'app/Auth/REQUEST_SIGNUP_SUCCESS';

export const REQUEST_PROFILE = 'app/Auth/REQUEST_PROFILE';
export const REQUEST_PROFILE_SUCCESS = 'app/Auth/REQUEST_PROFILE_SUCCESS';

export const REQUEST_PERMISSIONS = 'app/Auth/REQUEST_PERMISSIONS';
export const REQUEST_PERMISSIONS_SUCCESS = 'app/Auth/REQUEST_PERMISSIONS_SUCCESS';

export const REQUEST_UPDATE_PROFILE = 'app/Auth/REQUEST_UPDATE_PROFILE';
export const REQUEST_UPDATE_PROFILE_SUCCESS = 'app/Auth/REQUEST_UPDATE_PROFILE_SUCCESS';

export const REQUEST_DELETE_PROFILE = 'app/Auth/REQUEST_DELETE_PROFILE';
export const REQUEST_DELETE_PROFILE_SUCCESS = 'app/Auth/REQUEST_DELETE_PROFILE_SUCCESS';

export const REQUEST_VERIFICATION = 'app/Auth/REQUEST_VERIFICATION';
export const REQUEST_VERIFICATION_SUCCESS = 'app/Auth/REQUEST_VERIFICATION_SUCCESS';
export const SYNC_AUTH = 'app/Auth/SYNC_AUTH';
export const STOP_LOADING = 'app/Auth/STOP_LOADING';

export const REQUEST_NEW_TOKEN = 'app/Auth/REQUEST_NEW_TOKEN';
export const REQUEST_NEW_TOKEN_SUCCESS = 'app/Auth/REQUEST_NEW_TOKEN_SUCCESS';

export const REQUEST_CHANGE_PASSWORD = 'app/Auth/REQUEST_CHANGE_PASSWORD';
export const REQUEST_CHANGE_PASSWORD_SUCCESS = 'app/Auth/REQUEST_CHANGE_PASSWORD_SUCCESS';

export const REQUEST_FORGOT_PASSWORD = 'app/Auth/REQUEST_FORGOT_PASSWORD';
export const REQUEST_FORGOT_PASSWORD_SUCCESS = 'app/Auth/REQUEST_FORGOT_PASSWORD_SUCCESS';

export const REQUEST_RESET_PASSWORD = 'app/Auth/REQUEST_RESET_PASSWORD';
export const REQUEST_RESET_PASSWORD_SUCCESS = 'app/Auth/REQUEST_RESET_PASSWORD_SUCCESS';

export const SOCIAL_LOGIN_PREPARE = 'app/Auth/SOCIAL_LOGIN_PREPARE';
export const SOCIAL_LOGIN_REQUEST = 'app/Auth/SOCIAL_LOGIN_REQUEST';
export const SOCIAL_OAUTH_SIGNUP = 'app/Auth/SOCIAL_OAUTH_SIGNUP';
export const REQUEST_IDP_SIGNUP = 'app/Auth/REQUEST_IDP_SIGNUP';

